### ISSUE TITLE
Styling - hover on multiselect - doesn't work for IE 11

### ISSUE THREAD

**Issue by seeker25** [facuesr/react-multiselect-box#2]
Inside of MultiSelectBox.css 

.available-list .item:hover {
  background-color: #00ff004d;
}

.selected-list .item:hover {
  background-color: rgba(255, 0, 0, 0.2);
}

Should be:

.available-list .item:hover {
    background-color: rgba(0, 255, 0, 0.2);
}

.selected-list .item:hover {
  background-color: rgba(255, 0, 0, 0.2);
}

For some reason IE doesn't pick up the color.

**Comment by facuesr** [comment]
Hi @seeker25, it's fixed now.
